### ISSUE TITLE
El valor del dolar para la compra es incorrecto 

### ISSUE THREAD

**Issue by franciscopstec** [enzonotario/esjs-dolar-app#1]
El JSON devuelve el mismo valor del dólar para la venta que para la compra. En la web de Dolar Hoy, que es de la que supuestamente se toman estos datos, ambos valores son diferentes.

**Comment by enzonotario** [comment]
Hola @franciscopstec , gracias por informarlo.

¿Te refieres al Dólar Oficial, no? En tal caso, ya quedó corregido. Seguramente en el instante donde la API consultó el valor desde DolarHoy, los valores de Compra y Venta eran iguales, por lo tanto se propagó el error hacia DolarApi.com.

Para la próxima, puedes abrir un Issue en el Repositorio de [DolarApi](https://github.com/enzonotario/esjs-dolar-api), que es la API que finalmente proporciona los valores.

Saludos!
